### ISSUE TITLE
applyCvar for cellmodel (part PCa)

### ISSUE THREAD

**Issue by ay-d** [kit-cml/libCML#1]
@vondarkness , di fungsi applyCvar untuk cellmodel ORdstatic, ORddynamic, dan Tomek yang buat CONSTANTS[PCa]

![image](https://github.com/user-attachments/assets/c2ef14b1-3888-4f91-884e-c03baf44f6d0)

itu seharusnya **CONSTANTS[PCa_b]**

minta tolong diganti **PCa** jadi **PCa_b** di :
Ohara_Rudy_2011.cpp (line **659**)
Tomek_model.cpp (line **733**)
ohara_rudy_cipa_v1_2017.cpp (line **814**)

**Comment by vondarkness** [comment]
Resolved in commit ID [51aeb7c](https://github.com/kit-cml/libCML/commit/51aeb7c904522119fd851341a2f78a1b6431ce43)
